apiVersion: apps/v1
kind: Deployment
metadata:
  name: novelty-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: novelty-app
  template:
    metadata:
      labels:
        app: novelty-app
    spec:
      containers:
        - name: novelty-app
          image: ciaa/anomaly:0.1.0
          imagePullPolicy: Always
          resources:
            limits:
              memory: "2000Mi"
              cpu: "2000m"
          ports:
            - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: novelty-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: novelty-app
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: novelty-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: ionos.ingress-nginx.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: novelty-service
            port:
              number: 8501