name: Build and publish docker image to docker hub and deploy to K8s
on:
  push:
    branches:
      - master
    paths:
      - 'water_level_anomaly_detection/*.py'
      - 'pyproject.toml'
      - 'poetry.lock'
      - 'Dockerfile'
jobs:
  build-and-deploy: 
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            name=docker.io/ciaa/anomaly
          tags: |
            type=sha,format=short
      
      - name: Login to Dockerfile
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ciaa
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v4

      - name: Set K8s context
        uses: Azure/k8s-set-context@v4
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Update and Deploy to Kubernetes
        run: |
          sed -i "s|image: docker.io/ciaa/anomaly:.*|image: docker.io/ciaa/anomaly:${{ steps.meta.outputs.tags }}|" deploy/k8s/deployment.yml
          kubectl apply -f deploy/k8s/deployment.yml